language: java
jdk:
- openjdk8
sudo: required
before_deploy: mvn clean verify
branches:
  only:
  - develop
  - uat
  - prod
deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  access_key_id:
    develop: AKIAJQOD25TNB4GR4LFQ
    uat: AKIAJQOD25TNB4GR4LFQ
    prod: AKIAZOKKB636GOXML5BE
  secret_access_key:
    develop:
      secure: "yTu9XPDJvubWG3iwx1o2rwMHetHdQ07jIwXrYmFyHQmOdU+AVWMKujBi8JUQb/T9nxcQirR05//aeeZ4ZQ46RBT1LSmYNTCCDxHZwyxh3cEl3X7v+CCgJUQJgun+gubTYGDYXBwT9uOuqhZLmqzATyorKrGS1t6QXJs5QVQ7JpcgbCRPT10t2hYfRBV81b+5JtWVBcJj/B7qLfa61IYehlqnvfNDVZdn4TEJI2D+1FYndn/uTnrWRfe6LuWkB95hwzVw81HN8AxZxPFS61PDJc5Sm2bt/vNgnYyY4Eqm1pqZxSg3x6GlcNe0LuhtOq8eI/j2MBgMOesZsXDwPNf2NCdkE/703VHSODOOPUDfHkgkiVxXmyqA4+LtEmNXhDpm0Pn969FXdSpD3LSvDxl9agXHx79kwo1AbhGiZPq48zliPL7QnWxKkuPdC7wSi3d4J73+sjFll4AGlOcz0Pp+BVvowtUG1JkWnFIMlFbKcP3PP3KTpNmVDvieJZXy1bYK15ZTtrPSMZlruRyeRPqMFD13JcOdy4SSbXfF+3xIILYRRW7sabCW5Ccby4Q1H4q2WEQs/+5uYbsqrjW4XcI9ZOtbGbR5swDUivttY+K5G+6P+tZVVQRCvhhQ11i2VqWn21F+ob+onIu7SQnw2/gVaNFvAT6F8vALSXNQjfwfmwY="
    uat:
      secure: "yTu9XPDJvubWG3iwx1o2rwMHetHdQ07jIwXrYmFyHQmOdU+AVWMKujBi8JUQb/T9nxcQirR05//aeeZ4ZQ46RBT1LSmYNTCCDxHZwyxh3cEl3X7v+CCgJUQJgun+gubTYGDYXBwT9uOuqhZLmqzATyorKrGS1t6QXJs5QVQ7JpcgbCRPT10t2hYfRBV81b+5JtWVBcJj/B7qLfa61IYehlqnvfNDVZdn4TEJI2D+1FYndn/uTnrWRfe6LuWkB95hwzVw81HN8AxZxPFS61PDJc5Sm2bt/vNgnYyY4Eqm1pqZxSg3x6GlcNe0LuhtOq8eI/j2MBgMOesZsXDwPNf2NCdkE/703VHSODOOPUDfHkgkiVxXmyqA4+LtEmNXhDpm0Pn969FXdSpD3LSvDxl9agXHx79kwo1AbhGiZPq48zliPL7QnWxKkuPdC7wSi3d4J73+sjFll4AGlOcz0Pp+BVvowtUG1JkWnFIMlFbKcP3PP3KTpNmVDvieJZXy1bYK15ZTtrPSMZlruRyeRPqMFD13JcOdy4SSbXfF+3xIILYRRW7sabCW5Ccby4Q1H4q2WEQs/+5uYbsqrjW4XcI9ZOtbGbR5swDUivttY+K5G+6P+tZVVQRCvhhQ11i2VqWn21F+ob+onIu7SQnw2/gVaNFvAT6F8vALSXNQjfwfmwY="
    prod:
      secure: "Tk2pQCyST251h+N9OBHkL2oOzYFZKt5gGX6MtGYjxEEDj10r5UtOrmPQ59629qfGLMjjUG3Ag3WLTyWSTQ0kgh0ybj5pBS2ITqXh8FwMpYpT+8LzM+wujl1rHJkNGU9wYnnQMLZ16GpyxZKyY+JZMJhh/bM0+FUkQCcjBBZKXxJuU8kNjwc7DVUhUiBo5v4J/WinKiKQb3UNlZBmJYxuQbZQpzDjQ0FvmPS6jUVwx855rYXPqlyGYIPhQJ8Zg2a39/5ceUoIyi6O69GQnKVTMkoHKOy8SSaNAPTNy+Mszo1mU7jObJchhqwm3bU0g5WEzttpHet9HTxuo+2Rk6D/onTfsKoI5p5+Sr5S46M+BwsKwEYos1dIB+F8zNOKAXaxeXGX9pnXvhg/+mVvyvijEsYgnFVyE7Fepo7/Tv54KSaDZSh3k06aIix4UtZETFukOLi/S8R9htL6fznn4LuygUJgz8OerqVsICIODEwIuGhL5epeAHok8tWPDDfrVjYQt3vEdO6SEISnpljZUrkEc65Z46IGiSaFmhTV+rjnyxwNs4w/+nd/+GEWAwlL0+YUwZgS3VLtENX0wHqwQMsXiKb9MXZGVochRj5aAOVBOIf3ehEeKPt1yQyKroCOEYbzfX9om14gX4paSeSlXas0kv2b8/jYqqi/fE1jb1aN8PY="
  region: us-east-1
  app: BridgeServer2-application
  env: bridgeserver2-$TRAVIS_BRANCH
  bucket_name: org-sagebridge-bridgeserver2-deployment-$TRAVIS_BRANCH
  zip-file: target/BridgeServer2-2.0.war
  on:
    all_branches: true
